### ISSUE TITLE
CI 3

### ISSUE THREAD

**Issue by ghahabib** [monkenWu/TablesIgniter#2]
Hi
Does this addition work with the version CodeIgniter 3.1.11?
Thanks.

**Comment by monkenWu** [comment]
Hi, actually, this library was originally implemented in codeigniter3, but it is only for me use.
If you need this library, I will release the Codeigniter3 version in the near future, but it may be slightly different in use (because there are some differences between ci4 and ci3 on the query builder).

**Comment by ghahabib** [comment]
Thank you,
I hope that.

**Comment by ghahabib** [comment]
Hi, Is it possible to obtain the version compatible with the version 3.1.11?
Thanks.

**Comment by monkenWu** [comment]
hi，you can go to https://github.com/monkenWu/TablesIgniter_CI3 get CodeIgniter3 version of Tableslgniter.
[Guide And DEMO](https://tablesigniter-ci3.monken.tw/)
